### ISSUE TITLE
How to add autoPlay?

### ISSUE THREAD

**Issue by 7laria** [peng666/react-awesome-player#5]
i used opttion prop but it doesn't work

**Comment by feawesome** [comment]
> i used opttion prop but it doesn't work

Google changed its strategy：

[https://developers.google.com/web/updates/2017/09/autoplay-policy-changes](https://developers.google.com/web/updates/2017/09/autoplay-policy-changes)

you can add prop
```
{
  muted: true,
  autoplay: true
}
```
